# fly.toml file generated for fnc-id-redis on 2022-02-02T15:30:49+01:00

app = "fnc-id-redis"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/redis:6.2.6"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[mounts]]
  destination = "/data"
  source = "redis_server"

[metrics]
  port = 9091
  path = "/metrics"
